services:
  - type: web
    name: random-video-chat-app
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server/server.js
    envVars:
      - key: NODE_VERSION
        value: 14
    autoDeploy: true
